Сущности
Klaypexx/CookingRecipes pull request #1
Opened 2024-07-08 17:19 UTC by Klaypexx

Расписал сущности проекта

2024-07-08 18:55 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int Like { get; set; }
Это мы количество лайков храним?

2024-07-08 18:56 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int Like { get; set; }
Если да, то лучше это так не хранить, а вычислять.

2024-07-08 18:57 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public User User { get; set; }
Это автор рецепта?

2024-07-08 18:57 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public User User { get; set; }
Лучше тогда назвать `Author`

2024-07-08 19:03 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +
По какому принципу пробелами разделяешь?) Лучше лишними строками не разделять.

2024-07-08 19:03 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +
Закинь еще в проект `.editorconfig` с первого этапа практики. И придерживайся всегда одного стиля форматирования.

2024-07-08 19:04 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +    public string AvatarPath {  get; set; }
Тут, например, лишний пробел.

2024-07-08 19:06 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Ingredient.cs
> +public class Ingredient
У ингредиента могут быть составляющие? Например, смесь специй, мы будем указывать, из чего она состоит?

2024-07-08 19:07 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +    public Ingredient Ingredient { get; set; }
Будет ли шаг связан с рецептом?

2024-07-08 19:08 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +    public Ingredient Ingredient { get; set; }
Почему решил выделить ингредиенты?
А если это шаг вроде "Выпечь", где ингредиентов нет или "Смешать молоко и крупу", где 2 ингредиента?

2024-07-08 19:09 UTC, pklgn commented on CookingRecipesApi/Infrastructure.Migrations/AppDbContextFactory.cs
> +        //IConfiguration config = GetConfig();
Из конфига будешь ConnectionString доставать? Было бы круто.

2024-07-08 19:09 UTC, pklgn commented on CookingRecipesApi/Infrastructure.Migrations/AppDbContextFactory.cs
> +        var optionalBuilder = new DbContextOptionsBuilder<AppDbContext>();
var не используем.

2024-07-08 19:09 UTC, pklgn commented on CookingRecipesApi/Infrastructure.Migrations/Program.cs
> +        Console.WriteLine("Before migration");
Пока еще миграции не создал?

2024-07-08 19:10 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Database/Config/UserConfiguration.cs
> +    public class UserConfiguration
А что здесь будет за инфа?

2024-07-08 19:11 UTC, pklgn commented on CookingRecipesApi/Infrastructure.Migrations/Infrastructure.Migrations.csproj
> +		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
Эта ссылка нужна?

2024-07-08 19:14 UTC, pklgn requested changes
Предлагаю обсудить комменты в PR'е.

2024-07-09 19:17 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +    public User()
Для чего публичный конструктор? Для EF'а? EF может работать и с protected конструктором. Нужно стараться избегать public модификатора для инкапсуляции. Хотя protected так-то тоже не совсем хорошо, но это компромисс.

2024-07-09 19:23 UTC, pklgn commented on CookingRecipesApi/Application/Auth/Repositories/IUserRepository.cs
> +
Форматирование. Добавь `.editorconfig` и используй автоформатирование.

2024-07-09 19:27 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +        User user = new() { Name = body.Name, UserName = body.UserName, Password = body.Password };
Вот это лучше по отдельным строкам разбить. Опять же, поможет `.editorconfig`. Можно взять тот, который сейчас у ребят на летней практике. 
Пришлось загрузить в виде `editorconfig.txt`, переименуй на `.editorconfig`
[editorconfig.txt](https://github.com/user-attachments/files/16149366/editorconfig.txt)

2024-07-09 19:27 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +    [Route("username")]
Почему эндпоинт называется username, если мы получаем пользователя?
Ты придерживаешься REST?

2024-07-09 19:28 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Dto/AuthDto/RegisterDto.cs
> +
Лишняя строка

2024-07-09 19:30 UTC, pklgn commented on CookingRecipesApi/Domain/Domain.csproj
> +    <Nullable>disable</Nullable>
Почему disable, кстати? Вроде по умолчанию они enable, ты намеренно это сделал?)

2024-07-09 19:31 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Ingredient.cs
> +namespace Domain.Recipes.Entities;
Не хватает пустой строки.

2024-07-09 19:32 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public DateTime? CookingTime { get; set; }
Это время приготовления блюда?
Точно для этого нужен DateTime?
Можно посмотреть в сторону `TimeOnly`

2024-07-09 19:32 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public string ShortDescription { get; set; }
Почему в названии `Short`?

2024-07-09 19:37 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public List<User> FavouritedBy { get; set; }
Может завести таблицу Like, где будет пользователь и понравившийся ему рецепт?

2024-07-09 19:41 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +public class StepDescription
А номер шага где-то будет храниться?

2024-07-09 19:44 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +public class StepDescription
Может просто Step назвать?

2024-07-09 19:48 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int? Like { get; set; }
Точно стоит лайки хранить?

2024-07-09 19:52 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Database/Config/IngredientConfiguration.cs
> +        builder.ToTable("ingredient");
Почему решил переименовать на таблицу с маленькой буквы?

2024-07-09 19:53 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Database/Config/IngredientConfiguration.cs
> +            .HasColumnName("name")
HasColumnName тоже можно по сути не писать.
Или ты бы хотел именно с маленькой буквы видеть название столбцов?

2024-07-09 19:55 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Database/Config/TagConfiguration.cs
> +        builder.HasMany(u => u.Recipes)
Что  означает `u` и `a`?
Можно писать всегда одну переменную в таких функциях. Как вариант: `x`.

2024-07-09 19:58 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
Точно ли пользователя нужно помещать в папку Auth? Как будто бы аутентификация только часть логики, которая связана с пользователем.

2024-07-09 20:01 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Foundation/UnitOfWork.cs
Что значит Foundation?

2024-07-09 20:07 UTC, pklgn requested changes
Обрати внимание на форматирование)

2024-07-09 20:35 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int Like { get; set; }
По сути да, это переменная, которая хранит количество лайков. У каждого рецепта пишется сколько лайков он имеет и это число будет сохранено в этой переменной 
![Снимок экрана 2024-07-09 233520](https://github.com/Klaypexx/CookingRecipes/assets/68664576/0f23059e-c8f1-47c1-b8ce-fe8d1dc369c4)

2024-07-09 20:58 UTC, Klaypexx commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +
Кидали нам такой файл, но есть сомнения, что это не то
![Снимок экрана 2024-07-09 235720](https://github.com/Klaypexx/CookingRecipes/assets/68664576/52bfe09a-f0d8-481e-b841-3810e8718803)

2024-07-09 21:00 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +    public Ingredient Ingredient { get; set; }
Я его в целом выделял в отдельную сущность, чтобы как то хранить массив значений, так как шагов может быть много. Из курса бд говорили, что такое выделяется в отдельные сущности. Но возможно есть и другие пути решения.

2024-07-09 21:02 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +    public Ingredient Ingredient { get; set; }
По такой же логике, как и шаги
![Снимок экрана 2024-07-10 000151](https://github.com/Klaypexx/CookingRecipes/assets/68664576/4adad14b-1b21-4e53-a6b0-376edfae448b)

2024-07-09 21:05 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure.Migrations/AppDbContextFactory.cs
> +        //IConfiguration config = GetConfig();
Да, это пока была заглушка) У меня там еще проблема, что миграция н хочет инициализироваться в проекте Infrastructure.Migrations. 
![Снимок экрана 2024-07-10 000541](https://github.com/Klaypexx/CookingRecipes/assets/68664576/c075448a-6753-4085-854f-067dfe40996e)

2024-07-09 21:08 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure.Migrations/Infrastructure.Migrations.csproj
> +		<PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="8.0.0" />
Перекинул все зависимости с другого проекта, где миграция с  Infrastructure.Migrations работает, поэтому там могут быть и лишние. Как смогу с этим разобраться поудаляю лишние ссылки.

2024-07-09 21:35 UTC, Klaypexx commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +    public User()
Пока что я его использую только в регистрации 
User user = new() { Name = body.Name, UserName = body.UserName, Password = body.Password };

2024-07-09 21:37 UTC, Klaypexx commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +    public User()
Думал что он понадобиться в регистрации пользователя. Пока конструктор удалил.

2024-07-09 21:44 UTC, Klaypexx commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +    [Route("username")]
Переименовал на user.

2024-07-09 21:45 UTC, Klaypexx commented on CookingRecipesApi/Domain/Domain.csproj
> +    <Nullable>disable</Nullable>
Да, на практике всегда делали disable, мол, отключая null.

2024-07-09 21:47 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public DateTime? CookingTime { get; set; }
![Снимок экрана 2024-07-10 004647](https://github.com/Klaypexx/CookingRecipes/assets/68664576/08c62f56-efcc-41e9-99d7-0a34051969da)
вот эта часть

2024-07-09 21:47 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public DateTime? CookingTime { get; set; }
Да, вероятно там нужно только время, без даты.

2024-07-09 21:52 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public string ShortDescription { get; set; }
Возможно не самое лучшее название. На макете отвечает за краткое описание.
![Снимок экрана 2024-07-10 005236](https://github.com/Klaypexx/CookingRecipes/assets/68664576/ae829bf2-bbfe-43f6-8e72-228456245025)

2024-07-09 21:54 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public List<User> FavouritedBy { get; set; }
По сути за это отвечает Favourite. Связь много ко многим и там формируется таблица с id пользователя и рецептом.

2024-07-09 21:55 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +public class StepDescription
Номер шага я думал будет автоматом на фронтенде отображаться. У нас по сути лист шагов. И каждый элемент будет отдельным шагом помечаться автоматически.

2024-07-09 21:55 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +public class StepDescription
Но если будет нужно впишу переменную номера шана.

2024-07-09 22:01 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int? Like { get; set; }
У всех рецептов есть количество лайков. 
![Снимок экрана 2024-07-10 010046](https://github.com/Klaypexx/CookingRecipes/assets/68664576/5df81647-cb0a-4f4c-9f93-d4f7952d58e6)

2024-07-09 22:02 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure/Database/Config/IngredientConfiguration.cs
> +        builder.ToTable("ingredient");
У меня все таблицы идут с маленькой буквы.

2024-07-09 22:03 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure/Database/Config/IngredientConfiguration.cs
> +            .HasColumnName("name")
Делал по примеру из другого проекта, там все столбцы были с маленькой, поэтому да, сделал так.

2024-07-09 22:05 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure/Database/Config/TagConfiguration.cs
> +        builder.HasMany(u => u.Recipes)
Исправил.

2024-07-09 22:06 UTC, Klaypexx commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
Кирилл давай свой проект, у него в приложении пользователь лежал в Auth. С учетом того, что он говорил придерживаться его архитектуры, сделал также. 
![Снимок экрана 2024-07-10 010544](https://github.com/Klaypexx/CookingRecipes/assets/68664576/814db9b1-1154-4018-b406-fb1632c717e6)
/ 
![Снимок экрана 2024-07-10 010537](https://github.com/Klaypexx/CookingRecipes/assets/68664576/746c1968-7d4d-499f-a318-18c4b6ef1577)

2024-07-09 22:07 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure/Foundation/UnitOfWork.cs
Там, где лежит IUnitOfWork. Опять же, придерживался архитектуры приложения Кирилла.

2024-07-09 22:09 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int? Like { get; set; }
По сути конечно можно высчитывать через пользователей, но эта затея выглядит сложнее, чем просто переменная, которая будет меняться при каждом нажатии на лайк.

2024-07-09 22:10 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int? Like { get; set; }
И я забыл сделать похожую переменную для подсчета того, сколько людей добавило в закладки, хотя как по мне это вообще не надо подсчитывать.

2024-07-10 11:39 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Ingredient.cs
> +public class Ingredient
Думаю что нет, каждый раз он будет прописывать заново то, что входит в блюдо.

2024-07-11 20:27 UTC, pklgn commented on CookingRecipesApi/Domain/Domain.csproj
> +    <Nullable>disable</Nullable>
То есть ты не будешь использовать `null` в проекте? Я думаю, лучше сделать enabled, потому что null может понадобиться, например, для ситуаций, когда мы ищем объект и не находим его по заданным параметрам.

2024-07-11 20:30 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public string ShortDescription { get; set; }
Давай остановимся просто на Description. Потому что другого описания у нас нет. А ограничение по длине ты просто задашь в конфигурации `EntityTypeConfiguration`.

2024-07-11 20:39 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/StepDescription.cs
> +public class StepDescription
Лучше явно задать порядок отдельным полем, потому что сложно будет реализовывать, например, смену порядка шагов. С другой стороны, это вроде и не нужно по макетам, но лучше в явном виде хранить всю нужную инфу о сущности в самой сущности.

2024-07-11 20:57 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int? Like { get; set; }
Поле с лайком нужно выносить в отдельную таблицу. Тут можно вспомнить нормальные формы НФ. Например, НФ2, все неключевые атрибуты должны зависеть от первичного ключа. Количество лайков это динамическая история, которая никак не зависит от первичного ключа, потому что бесконтрольно меняется. 
Также тут момент насчет производительности возникает. В большинстве СУБД используется блокировка на уровне строки для обеспечения согласованности данных при одновременном доступе. Когда обновляется поле количества лайков, строка может быть заблокирована для других операций записи, что приводит к задержкам и снижению производительности. Если обновление количества лайков выполняется в рамках транзакции, это может удлинять время удержания блокировок. В результате другие транзакции, которые также пытаются обновить количество лайков для той же сущности, будут ожидать завершения первой транзакции, что увеличивает время отклика.

Поэтому лучше лайки хранить в отдельной таблице: в ней ты будешь просто инсертить строки, что не будет приводить к задержкам для получения данных.

2024-07-11 21:19 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
Хорошо, давай сделаем, как у Кирилла.

2024-07-11 21:32 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public int Like { get; set; }
про лайки отписал ниже:
Поле с лайком нужно выносить в отдельную таблицу. Тут можно вспомнить нормальные формы НФ. Например, НФ2, все неключевые атрибуты должны зависеть от первичного ключа. Количество лайков это динамическая история, которая никак не зависит от первичного ключа, потому что бесконтрольно меняется.
Также тут момент насчет производительности возникает. В большинстве СУБД используется блокировка на уровне строки для обеспечения согласованности данных при одновременном доступе. Когда обновляется поле количества лайков, строка может быть заблокирована для других операций записи, что приводит к задержкам и снижению производительности. Если обновление количества лайков выполняется в рамках транзакции, это может удлинять время удержания блокировок. В результате другие транзакции, которые также пытаются обновить количество лайков для той же сущности, будут ожидать завершения первой транзакции, что увеличивает время отклика.

Поэтому лучше лайки хранить в отдельной таблице: в ней ты будешь просто инсертить строки, что не будет приводить к задержкам для получения данных.

2024-07-11 21:35 UTC, pklgn commented on CookingRecipesApi/Application/Auth/Repositories/IUserRepository.cs
> +namespace Application.Auth.Repositories;
`namespace`'ы тоже надо отделять строками. Можно найти правило для editorconfig'а. Ну либо спросить у чатгпт)

2024-07-11 21:36 UTC, pklgn commented on CookingRecipesApi/Infrastructure/Migrations/20240709215845_Step.cs
Пустые миграции?

2024-07-16 18:52 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +public class AuthController : ControllerBase
Почему называется `Auth` контроллер, если сам роут называется `users`?

2024-07-16 18:55 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +        bool result = _passwordHasher.Verify( body.Password, user.Password );
Название переменной неочевидное. Результат чего имеется в виду? Нужно дать более однозначное название.

2024-07-16 18:57 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +            throw new Exception( "Failed to login" );
Базовое исключение точно норм бросать? Может написать кастомное исключение?

2024-07-16 18:57 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +            throw new Exception( "Failed to login" );
Если кинется исключение, то что произойдет с нашей программой?

2024-07-16 19:06 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +            throw new Exception( "Failed to login" );
Точно ли следует кидать исключение, если мы не залогинились?

2024-07-16 19:06 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +            throw new Exception( "Failed to login" );
Почему не кинуть `BadRequest`?

2024-07-16 19:10 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Controllers/AuthController.cs
> +            return BadRequest( new Exception( "Токен обновления не существует" ) );
Для чего в BadRequest кидать исключение? Почему текста недостаточно?

2024-07-16 19:19 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/FavouriteRecipe.cs
> +    public User User { get; set; }
Зачем использовать User в данной сущности?
Аналогичный вопрос к рецепту. В примере, который мы смотрели на созвоне, было иначе: https://learn.microsoft.com/en-us/ef/core/modeling/relationships/many-to-many#many-to-many-with-class-for-join-entity:~:text=Many%2Dto%2Dmany%20with%20class%20for%20join%20entity

2024-07-16 19:33 UTC, pklgn commented on CookingRecipesApi/CookingRecipesApi/Program.cs
> +var builder = WebApplication.CreateBuilder( args );
`var` не используем.

2024-07-16 19:44 UTC, pklgn commented on CookingRecipesApi/Domain/Auth/Entities/User.cs
> +    public List<Recipe> Recipes { get; set; }
Вроде же хотели выпиливать эти рецепты?

2024-07-16 19:53 UTC, pklgn commented on CookingRecipesApi/Infrastructure.Migrations/Program.cs
> +        new AppDbContextFactory().CreateDbContext( args ).Database.Migrate();
Тут будет выведен список примененных миграций?

2024-07-16 19:55 UTC, pklgn commented on CookingRecipesApi/Domain/Recipes/Entities/Like.cs
> +public class Like
Почему не сделал так же как и с RecipeTag'ом?

2024-07-17 18:35 UTC, Klaypexx commented on CookingRecipesApi/Infrastructure.Migrations/Program.cs
> +        new AppDbContextFactory().CreateDbContext( args ).Database.Migrate();
Да, у меня все миграции должны содержаться в Infrastructure.Migrations, но по какой-то причине они не могут туда импортироваться, выдает ошибку, поэтому пока поместил их просто в Infrastructure.

2024-07-21 19:55 UTC, pklgn commented on CookingRecipesApi/Application/Auth/Entities/IPasswordHasher.cs
> +    public bool Verify( string password, string hashedPassword );
Можно без `public`. Главное придерживаться единообразия. Если почти везде без модификатора доступа, то значит тут его быть не должно.

2024-07-21 19:56 UTC, pklgn commented on CookingRecipesApi/Application/Auth/Services/AuthService.cs
> +    private readonly IUnitOfWork _unitOfWork;
Почему тут `readonly`?

2024-07-21 20:16 UTC, pklgn commented on CookingRecipesApi/Application/Validation/AuthValidationRules.cs
> +    private readonly IUserRepository _userRepository;
В `AuthService` не было readonly модификатора. По сути обычно его стоит указывать везде.
Либо можно воспользоваться фичой .NET 8, которая называется Primary Constructor. Почитать можно [тут](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/primary-constructors). Довольно красивый и лаконичный код получается. Только если решишь использовать, то надо будет везде с ее применением зарефакторить, чтобы была последовательность в принятии решений и однородный код.

2024-07-26 08:13 UTC, k-sannikov reviewed
Вроде как все норм, осталось поправить комменты которые я отписал и можно идти дальше

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Auth/Entities/IAuthService.cs
> +namespace Application.Users.Entities;
этот файл надо бы вынести из Entities, т.к. это не доменная сущность, а интерфейс сервиса, надо поместить в Services

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Auth/Entities/IPasswordHasher.cs
> +namespace Application.Auth.Entities;
этот файл надо бы вынести из Entities, т.к. это не доменная сущность, а интерфейс сервиса, надо поместить в Services

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Auth/Entities/ITokenService.cs
> +namespace Application.Auth.Entities;
этот файл надо бы вынести из Entities, т.к. это не доменная сущность, а интерфейс сервиса, надо поместить в Services

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/FavouriteRecipe.cs
> +using Domain.Auth.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
Все это лишнее

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Like.cs
> +    /* Like()
комменты не оставляем в коде

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Like.cs
> +using System.Linq;
почистить лишние зависимости

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +﻿using System.ComponentModel.DataAnnotations.Schema;
почистить лишние зависимости

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +﻿using System.ComponentModel.DataAnnotations.Schema;
Вообще по всем доменным сущностям пройдись, у тебя много лишних зависимостей, которые не используются, их надо убрать

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Infrastructure/Auth/Utils/PasswordHasher.cs
> +public class PasswordHasher : IPasswordHasher
этот сервис можно сделать просто статическим классом и обойтись без интерфейса и без DI, что сократит кол-во кода и упростит его чтение
Плюс я бы поменял названия методов, сделал бы что-то типа GeneratePasswordHash и VerifyPasswordHash

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Infrastructure/Auth/Utils/PasswordHasher.cs
> +public class PasswordHasher : IPasswordHasher
и положил бы этот сервис в слой Application

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Auth/Services/AuthService.cs
> +    private IPasswordHasher _passwordHasher;
договорились, что такие моменты будем делать readonly

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Foundation/Entities/IUnitOfWork.cs
> +﻿namespace Application.Foundation.Entities;
Тут, как будто вообще entities неуместно. Советую вытащить этот интерфейс на уровень выше

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Foundation/Entities/IUnitOfWork.cs
> +﻿namespace Application.Foundation.Entities;
в инфраструктурном слое у тебя этот момент нормально сделан

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Application/Validation/AuthValidationRules.cs
> +
очень много неиспользуемых зависимостей, проверь вообще по всему проекту их

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public List<FavouriteRecipe> FavouritedBy { get; set; }
лучше FavouriteRecipes

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Domain/Recipes/Entities/Recipe.cs
> +    public List<Like> LikesCount { get; set; }
просто Likes

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Infrastructure/Foundation/UnitOfWork.cs
> +        public UnitOfWork(AppDbContext context)
форматирование

2024-07-26 08:13 UTC, k-sannikov commented on CookingRecipesApi/Infrastructure.Migrations/AppDbContextFactory.cs
> +        string connectionString = config.GetConnectionString( "CookingRecipes"); ;
форматирование

2024-07-26 08:21 UTC, k-sannikov commented on CookingRecipesApplication/CookingRecipes/src/Components/Form/TagsInput/TagsInput.tsx
> +          const handleCreate = (e: React.KeyboardEvent<HTMLInputElement>) => {
есть ощущение, что надо вытащить эту лямбду из верстки и подставлять в верстку чисто название функции и все, вроде как ничего не мешает это сделать

2024-07-26 08:27 UTC, k-sannikov commented on CookingRecipesApplication/CookingRecipes/src/Components/Modal/BaseModal/BaseModal.tsx
> +    // const onWrapperClick = (event: any) => {
комментарии стараемся не оставлять

2024-07-26 08:27 UTC, k-sannikov commented on CookingRecipesApplication/CookingRecipes/src/Components/Modal/LoginModal/LoginModal.tsx
> +    const validationSchema = Yup.object({
обсуждали, что можно вынести куда-то, в отдельный файл/папку

2024-07-26 11:40 UTC, Klaypexx commented on CookingRecipesApi/Domain/Recipes/Entities/Like.cs
> +    /* Like()
Оставлю тогда этот код здесь, после к нему вернусь 
`Like()
{
    List<Recipe> recipes = new List<Recipe>() { new(), new(), new() };


    var user = new User();


    IEnumerable<string> userRecipeIds = user.Likes
        .Select( z => z.Recipe )
        .Select( z => z.Id );

    List<Recipe> qqq = user.Likes
        .Select( x => recipes.IntersectBy( userRecipeIds, y => y.Id ) )
        .SelectMany( x => x )
        .ToList();
}`

2024-07-27 22:43 UTC, merged